### ISSUE TITLE
Latest create-jsx-email doesn't seem to work

### ISSUE THREAD

**Issue by Thiht** [shellscape/jsx-email#237]
- Component or Package Name: create-jsx-email
- Component or Package Version: v2.0.4
- `@jsxp-email/cli` Version?:
- Operating System (or Browser): macOS
- Node Version: v22.11.0
- Link to reproduction _(⚠️ read below)_: N/A, I just executed `npm create jsx-email`

### Expected Behavior

I want the template to be created

### Actual Behavior

I get this error: 

```
node:internal/fs/promises:638
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open '/Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/generators/templates/email.mustache'
    at async open (node:internal/fs/promises:638:25)
    at async readFile (node:internal/fs/promises:1238:14)
    at async createEmail (/Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/src/index.ts:65:20)
    at async run (/Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/src/index.ts:166:3) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/generators/templates/email.mustache'
}

Node.js v22.11.0
npm error code 1
npm error path /Users/thibaut/Developer
npm error command failed
npm error command sh -c create-jsx-email emails
npm error A complete log of this run can be found in: /Users/thibaut/.npm/_logs/2024-11-08T15_47_59_859Z-debug-0.log
```

The downloaded module doesn't seem complete:

```
➜  Developer ls /Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/generators/
ls: /Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/generators/: No such file or directory
➜  Developer ls /Users/thibaut/.npm/_npx/67e558cc413def57/node_modules/create-jsx-email/
LICENSE.md   README.md    bin          dist         package.json
```

### Additional Information

When I force install the previous version (`@2.0.3`) it works fine, it looks like an issue with the latest only

**Comment by shellscape** [comment]
Thanks for reporting. We're on it.

**Comment by shellscape** [comment]
Should be all fixed up.
